# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Graph-Maker.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# =====================================================

# Graph_Maker_v1.0
from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib.pyplot as plt

print("="*35)
print("\n  그래프 메이커 커맨더 창\n")
print("="*35)

# =====================================================

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(412, 240)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(70, 10, 311, 101))
        font = QtGui.QFont()
        font.setFamily("전주 완판본 순B")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.function_2 = QtWidgets.QPushButton(Dialog)
        self.function_2.setGeometry(QtCore.QRect(110, 150, 91, 61))
        self.function_2.setObjectName("function_2")
        self.function_1 = QtWidgets.QPushButton(Dialog)
        self.function_1.setGeometry(QtCore.QRect(10, 150, 91, 61))
        self.function_1.setObjectName("function_1")
        self.function_3 = QtWidgets.QPushButton(Dialog)
        self.function_3.setGeometry(QtCore.QRect(210, 150, 91, 61))
        self.function_3.setObjectName("function_3")
        self.function_4 = QtWidgets.QPushButton(Dialog)
        self.function_4.setGeometry(QtCore.QRect(310, 150, 91, 61))
        self.function_4.setObjectName("function_4")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 90, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Jua")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 64, 15))
        font = QtGui.QFont()
        font.setFamily("경기천년바탕 Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(320, 220, 91, 20))
        font = QtGui.QFont()
        font.setFamily("경기천년바탕 Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        # =====================================================

        # Button 클릭 시
        self.function_1.clicked.connect(self.Function_1)
        self.function_2.clicked.connect(self.Function_2)
        self.function_3.clicked.connect(self.Function_3)
        self.function_4.clicked.connect(self.Function_4)

        # =====================================================

    def retranslateUi(self, Dialog):                # 프로그램 화면
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Graph_Maker_v1.0"))
        self.label.setText(_translate("Dialog", "Graph Maker"))
        self.function_2.setText(_translate("Dialog", "이차함수"))
        self.function_1.setText(_translate("Dialog", "일차함수"))
        self.function_3.setText(_translate("Dialog", "삼차함수"))
        self.function_4.setText(_translate("Dialog", "사차함수"))
        self.label_2.setText(_translate("Dialog", "\"어떤 함수를 그릴 것인지 선택\""))
        self.label_5.setText(_translate("Dialog", "v1.0"))
        self.label_6.setText(_translate("Dialog", "by. Yoonmen"))
        # =====================================================

    def Function_1(self):
        plt.axvline(x=0, color='r')  # draw x =0 axes
        plt.axhline(y=0, color='r')  # draw y =0 axes
        c = int(input('\n일차항의 계수를 입력해주세요 : '))
        d = int(input('\n상수항을 입력해주세요 : '))
        x = [a for a in range(-5, 5)]
        y = [c * b ** 1 + d for b in range(-5, 5)]
        print('\n=> y = ', c, 'x + ', d)
        plt.plot(x, y)  # draw line
        plt.show()

    def Function_2(self):
        plt.axvline(x=0, color='r')  # draw x =0 axes
        plt.axhline(y=0, color='r')  # draw y =0 axes
        c = int(input('\n이차항의 계수를 입력해주세요 : '))
        d = int(input('\n일차항의 계수를 입력해주세요 : '))
        e = int(input('\n상수항을 입력해주세요 : '))
        x = [a for a in range(-5, 5)]
        y = [c * b ** 2 + d * b ** 1 + e for b in range(-5, 5)]
        print('\n=> y = ', c, 'x^2 + ', d, 'x^1 + ', e)
        plt.plot(x, y)  # draw line
        plt.show()

    def Function_3(self):
        plt.axvline(x=0, color='r')  # draw x =0 axes
        plt.axhline(y=0, color='r')  # draw y =0 axes
        c = int(input('\n삼차항의 계수를 입력해주세요 : '))
        d = int(input('\n이차항의 계수를 입력해주세요 : '))
        e = int(input('\n일차항의 계수를 입력해주세요 : '))
        f = int(input('\n상수항을 입력해주세요 : '))
        x = [a for a in range(-5, 5)]
        y = [c * b ** 3 + d * b ** 2 + e * b ** 1 + f for b in range(-5, 5)]
        print('\n=> y = ', c, 'x^3 + ', d, 'x^2 + ', e, 'x^1 + ', f)
        plt.plot(x, y)  # draw line
        plt.show()

    def Function_4(self):
        plt.axvline(x=0, color='r')  # draw x =0 axes
        plt.axhline(y=0, color='r')  # draw y =0 axes
        c = int(input('\n사차항의 계수를 입력해주세요 : '))
        d = int(input('\n삼차항의 계수를 입력해주세요 : '))
        e = int(input('\n이차항의 계수를 입력해주세요 : '))
        f = int(input('\n일차항의 계수를 입력해주세요 : '))
        g = int(input('\n상수항을 입력해주세요 : '))
        x = [a for a in range(-5, 5)]
        y = [c * b ** 3 + d * b ** 2 + e * b ** 1 + f for b in range(-5, 5)]
        print('\n=> y = ', c, 'x^4 + ', d, 'x^3 + ', e, 'x^2 + ', f, 'x^1 + ', g)
        plt.plot(x, y)  # draw line
        plt.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
